spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/mom_med
    username: postgres
    password: soojong9627
    hikari:
      maximum-pool-size: 10
      minimum-idle: 2
      connection-timeout: 10000

  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true

external:
  mfds:
    api-key: 5065306b2c991f4cc60c5538fd6ca6a264a3f54a654aff8b773d94b0ec7d989a
  hira:
    api-key: 5065306b2c991f4cc60c5538fd6ca6a264a3f54a654aff8b773d94b0ec7d989a
  kma:
    api-key: 5065306b2c991f4cc60c5538fd6ca6a264a3f54a654aff8b773d94b0ec7d989a
  gemini:
    api-key: AIzaSyBI857RD_6MBkggwsyBa0BXrFRGGHj6xPE
    model: gemini-2.5-flash-lite
    prompt-version: v1

app:
  encryption-key: za3zPt7124hpw/vGP7WQEGkfRD44sRerkcUVQ8zk2qs=
  etl:
    dur:
      enabled: true
      combo-path: drug_csv/의약품안전사용서비스(DUR)_병용금기 품목리스트 2025.6.csv
      elderly-path: drug_csv/의약품안전사용서비스(DUR)_노인주의 품목리스트 2025.6.csv
      elderly-nsaid-path: drug_csv/의약품안전사용서비스(DUR)_노인주의(해열진통소염제) 품목리스트 2025.6.csv

logging:
  level:
    org.hibernate.SQL: DEBUG
